# Generated by Django 4.1.2 on 2022-11-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='backorder_level',
            field=models.IntegerField(default=1, help_text='The number of items that may be backordered.', verbose_name='Backorder Level'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='preorder_level',
            field=models.IntegerField(default=1, help_text='The number of items that may be preorderable.', verbose_name='Preorder Level'),
        ),
    ]
