# Generated by Django 4.1.4 on 2023-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Other Services', max_length=50),
        ),
    ]
