# Generated by Django 4.1.4 on 2023-01-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
