# Generated by Django 4.1.4 on 2023-01-04 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0002_alter_service_order_alter_service_status'),
        ('billing', '0002_remove_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
