# Generated by Django 4.1.2 on 2022-12-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Declined', 'Declined'), ('Deleted', 'Deleted'), ('Void', 'Void')], default='Unpaid', max_length=50),
        ),
    ]
