# Generated by Django 4.1.2 on 2022-12-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
