# Generated by Django 4.1.2 on 2022-12-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_backorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='For Sale'),
        ),
    ]
