# Generated by Django 4.1.4 on 2023-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Catering', 'Catering'), ('Other Services', 'Other Service')], default='Catering', max_length=50),
        ),
    ]
