# Generated by Django 4.1.4 on 2023-01-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_order_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='service_type', to='services.type'),
            preserve_default=False,
        ),
    ]
