# Generated by Django 4.1.4 on 2023-01-09 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('orders', '0001_initial'),
        ('services', '0003_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.person'),
        ),
    ]
