# Generated by Django 4.1.4 on 2023-01-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0004_alter_service_order_alter_service_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.item'),
        ),
    ]
