# Generated by Django 4.1.2 on 2022-11-26 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Company Code')),
                ('contact_type', models.CharField(choices=[('Costumer', 'Costumer'), ('Vendor', 'Vendor')], default='Costumer', max_length=50)),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=70, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=200, verbose_name='Zip Code')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone Number')),
                ('webpage', models.CharField(blank=True, max_length=200, verbose_name='Webpage')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='contacts.company', verbose_name='Company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
