# Generated by Django 4.1.2 on 2022-12-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor')], default='Costumer', max_length=50),
        ),
    ]
