# Generated by Django 4.1.2 on 2022-12-06 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('production', '0002_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_ingredient', to='products.item', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_product', to='products.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='products.item', verbose_name='Item'),
        ),
    ]
